name: CI Test

on: [push, pull_request]

jobs:
  test:
    env:
      UNSPLASH_USERTOKEN: ${{ secrets.UNSPLASH_USERTOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: go test
        run: go test -v ./...
